# GENERAL ==============================

warning = { fg='alizarin' } # Editor warnings.
error = { fg='alizarin' } # Editor errors, like mis-typing a command.
info = { fg='yellow-leaf'} # Contextual info in diagnostic messages (LSP).
hint = { fg='sky-fall' } # Code diagnostics hints (LSP).
diagnostic = { fg='sky-fall' } # Code diagnostics in editing area (LSP).

# UI ==============================
# For styling helix itself.

'ui.background' = { bg='black' } # Default background color.
'ui.window' = { fg='light-charcoal' } # Window border between splits.
'ui.gutter' = { fg='sky-fall' } # Left gutter for diagnostics and breakpoints.

'ui.text' = { fg='cloud' } # Default text color.
'ui.text.focus' = {} # Selection highlight in buffer-picker or file-picker.
'ui.text.info' = {} # Info popup contents (space mode menu).

'ui.cursor' = { modifiers = ['reversed'] }
'ui.cursor.select' = { bg = 'white' }
'ui.cursor.insert' = { bg = 'white' }
'ui.cursor.match' = { fg = 'black', bg = 'white' }
'ui.cursor.primary' = { fg='black', bg='white'}
'ui.cursorline.primary' = { bg = 'burnt-charcoal' }

'ui.selection' = { fg='black', bg='belize' } # All currently selected text.
'ui.selection.primary' = { fg='black', bg='belize' } # The primary selection when there are multiple.

'ui.linenr' = { fg='light-charcoal' } # Line numbers.
'ui.linenr.selected' = { fg='cloud' } # Current line number.

'ui.virtual' = { } # Namespace for additions to the editing area.
'ui.virtual.ruler' = { } # Vertical rulers (colored columns in editing area).
'ui.virtual.whitespace' = { } # Whitespace markers in editing area.

'ui.statusline' = { fg='light-charcoal' } # Status line.
'ui.statusline.inactive' = { fg='light-charcoal' } # Status line in unfocused windows.
'ui.statusline.normal' = { fg='light-charcoal' } # Statusline mode during normal mode (only if editor.color-modes is enabled)
'ui.statusline.insert' = { fg='light-charcoal' } # Statusline mode during insert mode (only if editor.color-modes is enabled)
'ui.statusline.select' = { fg='light-charcoal' } # Statusline mode during select mode (only if editor.color-modes is enabled)

'ui.help' = { fg='light-charcoal' } # `:command` descriptions above the command line.

'ui.highlight' = { fg='alizarin' } # selected contents of symbol pickers (spc-s, spc-S) and current line in buffer picker (spc-b).

'ui.menu' = { fg='light-charcoal' } # Autocomplete menu.
'ui.menu.selected' = { fg='black', bg='cloud' } # Selected autocomplete item.

'ui.popup' = { bg='wood-charcoal' } # Documentation popups (space-k).
'ui.popup.info' = { } # Info popups box (space mode menu).


# SYNTAX HIGHLIGHTING ==============================
# All the keys here are Treesitter scopes.

'property' = { } # Regex group names.
'special' = { fg='light-charcoal' } # Special symbols e.g `?` in Rust, `...` in Hare.
'attribute' = { } # Class attributes, html tag attributes.

'type' = { fg='golden-haze' } # Variable type, like integer or string, including program defined classes, structs etc..
'type.builtin' = { fg='golden-haze' } # Primitive types of the language (string, int, float).
'type.enum.variant' = { fg='golden-haze' } # A variant of an enum.

'constructor' = { fg='golden-haze' } # Constructor method for a class or struct.

'constant' = { fg='sky-fall' } # Constant value
'constant.builtin' = { } # Special constants like `true`, `false`, `none`, etc.
'constant.builtin.boolean' = { fg='sky-fall' } # True or False.
'constant.character' = { } # Constant of character type.
'constant.character.escape' = { fg='light-charcoal' } # escape codes like \n.
'constant.numeric'  = { fg='wisteria' } # constant integer or float value.
'constant.numeric.integer' = { fg='wisteria' } # constant integer value.
'constant.numeric.float' = { fg='wisteria' } # constant float value.

'number' = { fg='lime-zing' }
'string' = { fg='lime-zing' } # String literal.
'string.regexp' = { } # Regular expression literal.
'string.special' = { } # Strings containing a path, URL, etc.
'string.special.path' = { } # String containing a file path.
'string.special.url' = { } # String containing a web URL.
'string.special.symbol' = { } # Erlang/Elixir atoms, Ruby symbols, Clojure keywords.

'comment' = { fg='light-charcoal' } # This is a comment.
'comment.line' = { fg='light-charcoal', bg='wood-charcoal' } # Line comments, like this.
'comment.block' = { fg='light-charcoal', bg='wood-charcoal' } # Block comments, like /* this */ in some languages.
'comment.block.documentation' = { fg='light-charcoal', bg='wood-charcoal' } # Doc comments, e.g '///' in rust.

'variable' = { } # Variable names.
'variable.builtin' = { fg='light-charcoal' } # Language reserved variables: `this`, `self`, `super`, etc.
'variable.parameter' = { } # Function parameters.
'variable.other.member' = { } # Fields of composite data types (e.g. structs, unions).

'label' = { fg='white', bg='asphalt' } # Loop labels, among other things.

'punctuation' = { fg='light-charcoal' } # Any punctuation symbol.
'punctuation.delimiter' = { fg='light-charcoal' } # Commas, colons or other delimiter depending on the language.
'punctuation.bracket' = { fg='light-charcoal' } # Parentheses, angle brackets, etc.

'keyword' = { fg='sky-fall' } # Language reserved keywords.
'keyword.control' = { fg='sky-fall' } # Control keywords.
'keyword.control.conditional' = { fg='sky-fall' } # `if`, `else`, `elif`.
'keyword.control.repeat' = { fg='sky-fall'} # `for`, `while`, `loop`.
'keyword.control.import' = { fg='sky-fall' } # `import`, `export` `use`.
'keyword.control.return' = { fg='sky-fall' } # `return` in most languages.
'keyword.control.exception' = { } # `try`, `catch`, `raise`/`throw` and related.
'keyword.operator' = { } # `or`, `and`, `in`.
'keyword.directive' = { } # Preprocessor directives (#if in C...).
'keyword.function' = { fg = 'sky-fall' } # The keyword to define a function: 'def', 'fun', 'fn'.

'operator' = { fg='#6699cc' } # Logical, mathematical, and other operators.

'function' = { fg='sky-fall' }
'function.builtin' = {}
'function.method' = {} # Class / Struct methods.
'function.macro' = { fg='light-charcoal' }
'function.special' = { } # Preprocessor function in C.

'tag' = { } # As in <body> for html, css tags.
'tag.error' = { } # Erroneous closing html tags.


# Markup ==============================
# Colors for markup languages, like Markdown or XML.

'markup.heading.1' = { } # Markdown heading 1 color.
'markup.heading.2' = { } # Markdown heading 2 color.
'markup.heading.3' = { } # Markdown heading 3 color.
'markup.heading.4' = { } # Markdown heading 4 color.
'markup.heading.5' = { } # Markdown heading 5 color.
'markup.heading.6' = { } # Markdown heading 6 color.
'markup.heading.marker' = { } # Hashtag color on Markdown headings.

'markup.list' = { }
'markup.list.numbered' = { } # Numbered list.
'markup.list.unnumbered' = { } # Bullet point list.

'markup.bold' = { } # Bold text.
'markup.italic' = { } # Italicised text.

'markup.link' = { }
'markup.link.url' = { } # Urls pointed to by links.
'markup.link.label' = { } # Non-URL link references.
'markup.link.text' = { } # URL and image descriptions in links.

'markup.quote' = { } # `> Quotes` in Markdown.


# Markup - Interface ==============================
# 'These scopes are used for theming the editor interface.'

'markup.normal' = { }
'markup.normal.completion' = { } # For completion doc popup ui.
'markup.normal.raw' = { } # For hover popup ui.

'markup.heading.completion' = { } # Headings for completion doc popup ui.
'markup.heading.raw' = { } # Headings for hover popup ui.

'markup.raw' = { } # Code block in Markdown.
'markup.raw.block' = { } # Multiline (```) codeblock in Markdown.
'markup.raw.inline' = { } # `Inline code block` in Markdown.
'markup.raw.inline.completion' = { } # ?
'markup.raw.inline.hover' = { } # ?

# Diff ==============================
# Version control changes.

'diff.plus' = { fg='lime-zing' } # Additions.
'diff.minus' = { fg='alizarin' } # Deletions.
'diff.delta' = { fg='white' } # Modifications.
'diff.delta.moved' = { fg='yellow-leaf' } # Renamed or moved files.


[palette] # Define your custom colors here.
white = '#ffffff'
cloud = '#ecf0f1'
black = '#000000'
alizarin = '#e74c3c'
asbestor = '#7f8c8d'
concrete = '#95a5a6'
asphalt = '#2c3e50'
belize = '#b5d5ff'
yellow-leaf = '#ffd2a7'
sky-fall = '#96cbfe'
wood-charcoal = '#202020'
light-charcoal = '#7c7c7c'
burnt-charcoal = '#121212'
lime-zing = '#cfffab'
golden-haze = '#ffffb6'
wisteria = '#ff73fd'
green-sea = '#99cc99'
